# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='\u7c7b\u578b')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('author', models.CharField(max_length=100, verbose_name='\u4f5c\u8005')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='\u53d1\u8868\u65e5\u671f')),
                ('home_display', models.BooleanField(default=False, verbose_name='\u9996\u9875\u663e\u793a')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='FatherMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u540d')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
                ('son', models.BooleanField(default=False, verbose_name='\u5b50\u83dc\u5355?')),
            ],
            options={
                'verbose_name': '\u4e00\u7ea7\u83dc\u5355',
                'verbose_name_plural': '\u4e00\u7ea7\u83dc\u5355',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='\u7c7b\u578b')),
                ('tagId', models.IntegerField(verbose_name='\u5e8f\u53f7')),
                ('intro', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='SonMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u540d')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seclab.FatherMenu', verbose_name='\u7236\u83dc\u5355')),
            ],
            options={
                'verbose_name': '\u4e8c\u7ea7\u83dc\u5355',
                'verbose_name_plural': '\u4e8c\u7ea7\u83dc\u5355',
            },
        ),
    ]
