# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatherMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u540d')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
                ('son', models.BooleanField(default=False, verbose_name='\u5b50\u83dc\u5355?')),
            ],
            options={
                'verbose_name': '\u4e00\u7ea7\u83dc\u5355',
                'verbose_name_plural': '\u4e00\u7ea7\u83dc\u5355',
            },
        ),
        migrations.CreateModel(
            name='SlideImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
                ('alt', models.CharField(max_length=100, verbose_name='\u66ff\u6362\u6587\u5b57')),
                ('order', models.IntegerField(unique=True, verbose_name='\u987a\u5e8f')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u6ed1\u52a8\u56fe\u7247',
                'verbose_name_plural': '\u9996\u9875\u6ed1\u52a8\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='SonMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u83dc\u5355\u540d')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seclab.FatherMenu', verbose_name='\u7236\u83dc\u5355')),
            ],
            options={
                'verbose_name': '\u4e8c\u7ea7\u83dc\u5355',
                'verbose_name_plural': '\u4e8c\u7ea7\u83dc\u5355',
            },
        ),
    ]
