# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimg',
            name='order',
        ),
    ]
