# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0002_remove_slideimg_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='\u7c7b\u578b')),
                ('tagId', models.IntegerField(verbose_name='\u5e8f\u53f7')),
                ('intro', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('slug', models.CharField(db_index=True, max_length=100, verbose_name='\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u56fe\u7247',
                'verbose_name_plural': '\u56fe\u7247',
            },
        ),
        migrations.DeleteModel(
            name='SlideImg',
        ),
    ]
