# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
