# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0005_auto_20160518_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 3, 9, 59, 99000, tzinfo=utc), max_length=100, verbose_name='\u4f5c\u8005'),
            preserve_default=False,
        ),
    ]
