# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0006_auto_20160518_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
