# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seclab', '0007_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='\u53d1\u8868\u65e5\u671f'),
        ),
    ]
